// <auto-generated />
using System;
using AromaCoffee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AromaCoffee.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321191803_FixImageNames")]
    partial class FixImageNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AromaCoffee.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AromaCoffee.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AromaCoffee.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AromaCoffee.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Кава",
                            Description = "Міцна класична кава",
                            ImageUrl = "/images/espresso.jpg",
                            IsAvailable = true,
                            Name = "Еспресо",
                            Price = 45m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Кава",
                            Description = "Ароматна чорна кава",
                            ImageUrl = "/images/americano.jpg",
                            IsAvailable = true,
                            Name = "Американо",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Кава",
                            Description = "Кава з ніжною молочною пінкою",
                            ImageUrl = "/images/cappuccino.jpg",
                            IsAvailable = true,
                            Name = "Капучино",
                            Price = 65m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Кава",
                            Description = "М’яка кава з молоком",
                            ImageUrl = "/images/latte.jpg",
                            IsAvailable = true,
                            Name = "Лате",
                            Price = 70m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Кава",
                            Description = "Кава із шоколадним смаком",
                            ImageUrl = "/images/mocha.jpg",
                            IsAvailable = true,
                            Name = "Мокачино",
                            Price = 75m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Кава",
                            Description = "Ніжна кава з вершковим смаком",
                            ImageUrl = "/images/raf.jpg",
                            IsAvailable = true,
                            Name = "Раф",
                            Price = 85m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Кава",
                            Description = "Солодкий гарячий напій",
                            ImageUrl = "/images/hotchocolate.jpg",
                            IsAvailable = true,
                            Name = "Гарячий шоколад",
                            Price = 80m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Кава",
                            Description = "Ароматний чай на вибір",
                            ImageUrl = "/images/tea.jpg",
                            IsAvailable = true,
                            Name = "Чай",
                            Price = 40m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Холодні напої",
                            Description = "Холодна чорна кава",
                            ImageUrl = "/images/iceamericano.jpg",
                            IsAvailable = true,
                            Name = "Айс Американо",
                            Price = 70m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Холодні напої",
                            Description = "Холодна кава з молоком",
                            ImageUrl = "/images/icelatte.jpg",
                            IsAvailable = true,
                            Name = "Айс Лате",
                            Price = 80m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Холодні напої",
                            Description = "Прохолодний кавовий напій",
                            ImageUrl = "/images/frappe.jpg",
                            IsAvailable = true,
                            Name = "Фрапе",
                            Price = 90m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Холодні напої",
                            Description = "Освіжаючий напій",
                            ImageUrl = "/images/lemonade.jpg",
                            IsAvailable = true,
                            Name = "Лимонад",
                            Price = 60m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Холодні напої",
                            Description = "Солодкий прохолодний коктейль",
                            ImageUrl = "/images/milkshake.jpg",
                            IsAvailable = true,
                            Name = "Молочний коктейль",
                            Price = 85m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Холодні напої",
                            Description = "Свіжовичавлений сік",
                            ImageUrl = "/images/orangefresh.jpg",
                            IsAvailable = true,
                            Name = "Апельсиновий фреш",
                            Price = 95m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Десерти",
                            Description = "Ніжний вершковий десерт",
                            ImageUrl = "/images/cheesecake.jpg",
                            IsAvailable = true,
                            Name = "Чізкейк",
                            Price = 95m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Десерти",
                            Description = "Класичний італійський десерт",
                            ImageUrl = "/images/tiramisu.jpg",
                            IsAvailable = true,
                            Name = "Тірамісу",
                            Price = 100m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Десерти",
                            Description = "Хрусткий круасан із ніжною начинкою",
                            ImageUrl = "/images/croissant.jpg",
                            IsAvailable = true,
                            Name = "Круасан",
                            Price = 55m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Десерти",
                            Description = "Насичений шоколадний десерт",
                            ImageUrl = "/images/cake.jpg",
                            IsAvailable = true,
                            Name = "Шоколадний торт",
                            Price = 110m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Десерти",
                            Description = "Солодкий пончик з глазур’ю",
                            ImageUrl = "/images/donut.jpg",
                            IsAvailable = true,
                            Name = "Пончик",
                            Price = 55m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Десерти",
                            Description = "Легкий французький десерт",
                            ImageUrl = "/images/macaron.jpg",
                            IsAvailable = true,
                            Name = "Макарон",
                            Price = 35m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Десерти",
                            Description = "Шоколадний вологий десерт",
                            ImageUrl = "/images/brownie.jpg",
                            IsAvailable = true,
                            Name = "Брауні",
                            Price = 65m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Десерти",
                            Description = "М’який кекс до кави",
                            ImageUrl = "/images/muffin.jpg",
                            IsAvailable = true,
                            Name = "Маффін",
                            Price = 50m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Десерти",
                            Description = "Заварне тістечко з кремом",
                            ImageUrl = "/images/eclair.jpg",
                            IsAvailable = true,
                            Name = "Еклер",
                            Price = 60m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Десерти",
                            Description = "Пишні панкейки з топінгом",
                            ImageUrl = "/images/pancakes.jpg",
                            IsAvailable = true,
                            Name = "Панкейки",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AromaCoffee.Models.OrderItem", b =>
                {
                    b.HasOne("AromaCoffee.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AromaCoffee.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AromaCoffee.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AromaCoffee.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AromaCoffee.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AromaCoffee.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
